import React from 'react';
import {
  View,
  Button,
  Flex,
  Heading,
  Text,
  Link,
  ProgressCircle
} from '@adobe/react-spectrum';
import { getHealthIcon } from '../../constants';
import { CopyableValue } from '@assurance/common-utils';
import Card from '../atoms/card';
import { useECID, useSelectedClientPushToken } from '../../hooks/useClientInfo';
import useClientValidationStatus from '../../hooks/useClientValidationStatus';
import { openHelpUrl, renderValue } from '../../utils/utils';
import { useOpenExperienceUrl } from '../../hooks/useOpenExperienceUrl';
import LiveActivitiesValidationSection from './live-activities-validation-section';

// Types
type ClientValidationStatus = 
  | 'edge-not-configured'
  | 'messaging-not-configured'
  | 'messaging-not-installed'
  | 'messaging-not-installed-android'
  | 'messaging-not-installed-ios'
  | 'no-ecid'
  | 'no-token'
  | 'no-token-android'
  | 'no-token-ios'
  | 'loading'
  | false; // false = valid state

type HealthStatus = 'valid' | 'invalid';

interface DataRow {
  label: string;
  value: string | null | undefined;
  showCopy: boolean;
  isLongData?: boolean;
}

interface ClientValidationWidgetProps {
  [key: string]: any; // For extra props
}

// Constants
const BUTTON_LABELS = {
  ecid: 'Ecid',
  token: 'Push Token',
  viewCatalog: 'View Extension Catalog',
  viewInstalled: 'View Installed Extensions',
  viewPublishing: 'View Publishing Flow',
  androidSetup: 'Setup Android Apps for Messaging',
  iosSetup: 'Article: Asking Permission to Use Notifications'
} as const;

const STATUS_MESSAGES = {
  'edge-not-configured': 'Edge Not Configured',
  'messaging-not-configured': 'Messaging Not Configured',
  'messaging-not-installed': 'Messaging Extension Not Initialized',
  'no-ecid': 'No ECID Detected',
  'no-token': 'Push Token Not Captured',
  'loading': 'Loading...',
  false: 'Device Configured and Push Token Detected'
} as const;

const STATUS_DETAILS = {
  'no-ecid':
    "The ECID is automatically generated by the SDK. Missing this event generally means that either the AEP SDK or the Assurance SDK hasn't been initialized correctly."
} as const;

const MSG_NOT_INSTALLED = {
  para1:
    "It appears you haven't properly installed and initiated the Messaging extension in your application. Make you've done the following steps:",
  androidAddStep: 'Add the Messaging extension dependency to your ',
  androidRegisterStepPre: 'Include the API call to register the Messaging extension in your',
  androidRegisterStepPost: 'method:',
  forFull: 'For the full instructions',
  importStep: 'Import the Messaging extension:',
  iosAddStep: 'Add the Messaging extension dependency to your Podfile',
  iosRegisterStepPre: 'Include the API call to register the Messaging extension in your',
  iosRegisterStepPost: 'method:',
  visitLaunch: 'visit the Launch Environments page.'
};

const MSG_NO_TOKEN = {
  appNotSetup: "App wasn't setup correctly for messaging",
  androidSetup: 'Setup Android Apps for Messaging',
  iosSetup: 'Article: Asking Permission to Use Notifications',
  missingSDK: 'Missing SDK call in',
  para1: "The Push ID wasn't detected on the device. This could be for several reasons:",
  userDeclined: 'User declined receiving push notifications'
};

const MSG_NO_EDGE = {
  para1:
    "It appears you haven't configured your Edge extension in Launch. First, make sure you have installed and configured the extension.",
  para2: 'Next, make sure the configuration has been published using the Publishing flow.',
  para3Pre: "Finally, make sure you aren't overriding the",
  para3Post: 'configuration value in your app code.'
};

const MSG_NO_CONFIG = {
  para1:
    "It appears you haven't configured your Messaging extension in Launch. First, make sure you have installed and configured the extension.",
  para2: 'Next, make sure the configuration has been published using the Publishing flow.',
  para3Pre: "Finally, make sure you aren't overriding the",
  para3Post: 'configuration value in your app code.'
};

// Utility functions
const getHealthStatus = (status: ClientValidationStatus | string | boolean): HealthStatus => {
  return !status ? 'valid' : 'invalid';
};

const getStatusMessage = (status: ClientValidationStatus | string | boolean): string => {
  if (!status) return STATUS_MESSAGES.false;
  if (String(status).indexOf('messaging-not-installed') !== -1) {
    return STATUS_MESSAGES['messaging-not-installed'];
  }
  if (String(status).indexOf('no-token') !== -1) {
    return STATUS_MESSAGES['no-token'];
  }
  return STATUS_MESSAGES[status as keyof typeof STATUS_MESSAGES] || '';
};

const getStatusDetails = (status: ClientValidationStatus | string | boolean): string | undefined => {
  return STATUS_DETAILS[status as keyof typeof STATUS_DETAILS];
};


// Component for rendering status-specific details
const StatusDetailsRenderer: React.FC<{
  status: ClientValidationStatus | string | boolean;
  openExpUrl: (params: { mode: string }) => void;
}> = ({ status, openExpUrl }) => {
  const renderMessagingNotInstalled = () => (
    <div>
      <div>{MSG_NOT_INSTALLED.para1}</div>
      {status === 'messaging-not-installed-android' ? (
        <ol>
          <li>
            {MSG_NOT_INSTALLED.androidAddStep}
            <i>build.gradle</i>
            <br />
            <br />
          </li>
          <li>
            {MSG_NOT_INSTALLED.importStep}
            <pre>
              <code>import com.adobe.marketing.mobile.Messaging;</code>
            </pre>
          </li>
          <li>
            {MSG_NOT_INSTALLED.androidRegisterStepPre} <i>onCreate()</i>{' '}
            {MSG_NOT_INSTALLED.androidRegisterStepPost}
            <pre>
              <code>Messaging.registerExtension();</code>
            </pre>
          </li>
        </ol>
      ) : (
        <ol>
          <li>
            {MSG_NOT_INSTALLED.iosAddStep}
            <br />
            <br />
          </li>
          <li>
            {MSG_NOT_INSTALLED.importStep}
            <pre>
              <code>import AEPMessaging</code>
            </pre>
          </li>
          <li>
            {MSG_NOT_INSTALLED.iosRegisterStepPre} <i>onCreate()</i>{' '}
            {MSG_NOT_INSTALLED.iosRegisterStepPost}
            <pre>
              <code>AEPMessaging.registerExtension();</code>
            </pre>
          </li>
        </ol>
      )}
      <div>
        {MSG_NOT_INSTALLED.forFull}&nbsp;
        <Link data-testid="openEnvironments" onPress={() => openExpUrl({ mode: 'environments' })}>
          {MSG_NOT_INSTALLED.visitLaunch}
        </Link>
      </div>
    </div>
  );

  const renderNoToken = () => (
    <div>
      <div>{MSG_NO_TOKEN.para1}</div>
      {status === 'no-token-android' ? (
        <ol>
          <li>
            {MSG_NO_TOKEN.appNotSetup}
            <View margin="size-200">
              <Button
                data-testid="openHelp"
                onPress={() => openHelpUrl({ mode: 'setupAndroid' })}
                variant="secondary"
              >
                <Text>{BUTTON_LABELS.androidSetup}</Text>
              </Button>
            </View>
          </li>
          <li>
            {MSG_NO_TOKEN.missingSDK} <i>FirebaseMessaging.getInstance().getToken()</i>:
            <br />
            <pre>
              <code>MobileCore.setPushIdentifier(token);</code>
            </pre>
          </li>
        </ol>
      ) : (
        <ol>
          <li>
            {MSG_NO_TOKEN.appNotSetup}
            <View margin="size-200">
              <Button
                data-testid="openHelp"
                onPress={() => openHelpUrl({ mode: 'setupIos' })}
                variant="secondary"
              >
                <Text>{BUTTON_LABELS.iosSetup}</Text>
              </Button>
            </View>
          </li>
          <li>{MSG_NO_TOKEN.userDeclined}</li>
          <li>
            {MSG_NO_TOKEN.missingSDK} <i>didRegisterForRemoteNotificationsWithDeviceToken</i>:
            <br />
            <pre>
              <code>MobileCore.setPushIdentifier(token);</code>
            </pre>
          </li>
        </ol>
      )}
    </div>
  );

  const renderEdgeNotConfigured = () => (
    <div>
      <div>{MSG_NO_EDGE.para1}</div>
      <Flex margin="size-200" gap="size-100" direction="column">
        <span>
          <Button
            data-testid="viewInstalled"
            variant="secondary"
            onPress={() => openExpUrl({ mode: 'installed' })}
          >
            <Text>{BUTTON_LABELS.viewInstalled}</Text>
          </Button>
        </span>
        <span>
          <Button
            data-testid="viewCatalog"
            variant="secondary"
            onPress={() => openExpUrl({ mode: 'catalog' })}
          >
            <Text>{BUTTON_LABELS.viewCatalog}</Text>
          </Button>
        </span>
      </Flex>
      <div>{MSG_NO_EDGE.para2}</div>
      <View margin="size-200">
        <Button
          data-testid="viewPublishing"
          variant="secondary"
          onPress={() => openExpUrl({ mode: 'publishing' })}
        >
          <Text>{BUTTON_LABELS.viewPublishing}</Text>
        </Button>
      </View>
      <div>
        {MSG_NO_EDGE.para3Pre} <i>edge.configId</i> {MSG_NO_EDGE.para3Post}
      </div>
    </div>
  );

  const renderMessagingNotConfigured = () => (
    <div>
      <div>{MSG_NO_CONFIG.para1}</div>
      <Flex margin="size-200" gap="size-100" direction="column">
        <span>
          <Button
            data-testid="viewInstalled"
            onPress={() => openExpUrl({ mode: 'installed' })}
            variant="secondary"
          >
            <Text>{BUTTON_LABELS.viewInstalled}</Text>
          </Button>
        </span>
        <span>
          <Button
            data-testid="viewCatalog"
            onPress={() => openExpUrl({ mode: 'catalog' })}
            variant="secondary"
          >
            <Text>{BUTTON_LABELS.viewCatalog}</Text>
          </Button>
        </span>
      </Flex>
      <div>{MSG_NO_CONFIG.para2}</div>
      <View margin="size-200">
        <Button
          data-testid="viewPublishing"
          onPress={() => openExpUrl({ mode: 'publishing' })}
          variant="secondary"
        >
          <Text>{BUTTON_LABELS.viewPublishing}</Text>
        </Button>
      </View>
      <div>
        {MSG_NO_CONFIG.para3Pre} <i>messaging.*</i> {MSG_NO_CONFIG.para3Post}
      </div>
    </div>
  );

  const renderDefaultDetails = () => {
    const statusDetails = getStatusDetails(status);
    return statusDetails ? <div>{statusDetails}</div> : null;
  };

  // Render status-specific details
  if (String(status).indexOf('messaging-not-installed') === 0) {
    return renderMessagingNotInstalled();
  }
  if (String(status).indexOf('no-token') === 0) {
    return renderNoToken();
  }
  if (status === 'edge-not-configured') {
    return renderEdgeNotConfigured();
  }
  if (status === 'messaging-not-configured') {
    return renderMessagingNotConfigured();
  }
  return renderDefaultDetails();
};

/**
 * Renders client validation widget with device information and status details.
 */
const ClientValidationWidget: React.FC<ClientValidationWidgetProps> = ({ ...extraProps }) => {
  const ecid = useECID();
  const token = useSelectedClientPushToken();
  const status = useClientValidationStatus();
  const isLoading = status === 'loading';
  const { openExpUrl } = useOpenExperienceUrl();

  // Data rows for ECID and Push Token
  const dataRows: DataRow[] = [
    {
      label: BUTTON_LABELS.ecid,
      value: ecid,
      showCopy: true
    },
    {
      label: BUTTON_LABELS.token,
      value: token,
      showCopy: true,
      isLongData: true
    }
  ];

  const statusMessage = getStatusMessage(status);
  const healthStatus = getHealthStatus(status);

  return (
    <View>
      <Card {...extraProps}>
        <Heading marginTop="size-0">Client</Heading>
        {isLoading ? (
          <Flex justifyContent="center" alignItems="center" height="100px">
            <ProgressCircle aria-label="Loading…" isIndeterminate />
          </Flex>
        ) : (
          <>
            <Text>This is the messaging details found in the client at the time of the connection to this Assurance session.</Text>
            <Flex gap="size-100" alignItems="center" marginTop="size-200">
              {getHealthIcon(healthStatus, 'L')}
              <Heading level={4}>{statusMessage}</Heading>
            </Flex>
            
            <View marginTop="size-200">
              <StatusDetailsRenderer
                status={status}
                openExpUrl={openExpUrl}
              />
            </View>
            
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 16 }}>
              <tbody>
                {dataRows.map(row => (
                  <tr key={row.label} style={{ borderBottom: '1px solid #e1e1e1' }}>
                    <td style={{ fontWeight: 500, padding: '12px 16px' }}>{row.label}</td>
                    <td
                      style={{
                        padding: '12px 16px',
                        maxWidth: row.isLongData ? 300 : undefined,
                        wordBreak: row.isLongData ? 'break-all' : undefined
                      }}
                    >
                      {row.showCopy ? <CopyableValue value={row.value} /> : renderValue(row.value)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>  
            
            {/* Live Activities Validation Section */}
            <View marginTop="size-300">
              <View paddingTop="size-200">
                <LiveActivitiesValidationSection />
              </View>
            </View>
          </>
        )}
      </Card>
    </View>
  );
};

export default ClientValidationWidget;
