import React, { useMemo } from 'react';
import {
  View,
  Button,
  Flex,
  Heading,
  Text,
  Link,
  ProgressCircle
} from '@adobe/react-spectrum';
import Card from '../atoms/card';
import { getHealthIcon } from '../../constants';
import { CopyableValue } from '../atoms/CopyableValue';
import { renderValue } from '../../utils/utils';
import useClientValidationStatus from '../../hooks/useClientValidationStatus';
import { useECID, useSelectedClientPushToken } from '../../hooks/useClientInfo';
import LiveActivitiesValidationSection from './live-activities-validation-section';

const MSG = {
  ecid: 'Ecid',
  unknown: 'unknown',
  title: 'Client',
  info: 'This is the messaging details found in the client at the time of the connection to this Assurance session.',
  token: 'Push Token',
  viewCatalog: 'View Extension Catalog',
  viewInstalled: 'View Installed Extensions',
  viewPublishing: 'View Publishing Flow'
};

const STATUS_MESSAGE = {
  'edge-not-configured': 'Edge Not Configured',
  'messaging-not-configured': 'Messaging Not Configured',
  'messaging-not-installed': 'Messaging Extension Not Initialized',
  'no-ecid': 'No ECID Detected',
  'no-token': 'Push Token Not Captured',
  valid: 'Device Configured and Push Token Detected'
};

const STATUS_DETAILS = {
  'no-ecid':
    "The ECID is automatically generated by the SDK. Missing this event generally means that either the AEP SDK or the Assurance SDK hasn't been initialized correctly."
};

const MSG_NOT_INSTALLED = {
  para1:
    "It appears you haven't properly installed and initiated the Messaging extension in your application. Make you've done the following steps:",
  androidAddStep: 'Add the Messaging extension dependency to your ',
  androidRegisterStepPre: 'Include the API call to register the Messaging extension in your',
  androidRegisterStepPost: 'method:',
  forFull: 'For the full instructions',
  importStep: 'Import the Messaging extension:',
  iosAddStep: 'Add the Messaging extension dependency to your Podfile',
  iosRegisterStepPre: 'Include the API call to register the Messaging extension in your',
  iosRegisterStepPost: 'method:',
  visitLaunch: 'visit the Launch Environments page.'
};

const MSG_NO_TOKEN = {
  appNotSetup: "App wasn't setup correctly for messaging",
  androidSetup: 'Setup Android Apps for Messaging',
  iosSetup: 'Article: Asking Permission to Use Notifications',
  missingSDK: 'Missing SDK call in',
  para1: "The Push ID wasn't detected on the device. This could be for several reasons:",
  userDeclined: 'User declined receiving push notifications'
};

const MSG_NO_EDGE = {
  para1:
    "It appears you haven't configured your Edge extension in Launch. First, make sure you have installed and configured the extension.",
  para2: 'Next, make sure the configuration has been published using the Publishing flow.',
  para3Pre: "Finally, make sure you aren't overriding the",
  para3Post: 'configuration value in your app code.'
};

const MSG_NO_CONFIG = {
  para1:
    "It appears you haven't configured your Messaging extension in Launch. First, make sure you have installed and configured the extension.",
  para2: 'Next, make sure the configuration has been published using the Publishing flow.',
  para3Pre: "Finally, make sure you aren't overriding the",
  para3Post: 'configuration value in your app code.'
};

const chooseStatus = status => (!status ? 'valid' : 'invalid');

const chooseStatusMessage = status => {
  if (!status) return STATUS_MESSAGE.valid;
  if ((status || '').indexOf('messaging-not-installed') !== -1)
    return STATUS_MESSAGE['messaging-not-installed'];
  if ((status || '').indexOf('no-token') !== -1) 
    return STATUS_MESSAGE['no-token'];
  return STATUS_MESSAGE[status] || '';
};

const chooseStatusDetails = status => STATUS_DETAILS[status];

// TODO: Implement these functions import the functionality of open.app.saga.js
const onOpenCatalog = () => {};
const onOpenEnvironments = () => {};
const onOpenInstalled = () => {};
const onOpenPublishing = () => {};
const onSetupAndroid = () => {};
const onSetupIos = () => {};

const DeviceWidget = ({ ...extraProps }) => {
  const ecid = useECID();
  const token = useSelectedClientPushToken();
  const status = useClientValidationStatus();
  const isLoading = status === 'loading';
  // Data rows for ECID and Push Token
  const dataRows = useMemo(
    () => [
      {
        label: MSG.ecid,
        value: ecid,
        showCopy: true
      },
      {
        label: MSG.token,
        value: token,
        showCopy: true,
        isLongData: true
      }
    ],
    [ecid, token]
  );

  // Status details rendering
  let statusDetails: React.ReactNode = null;
  if ((status || '').indexOf('messaging-not-installed') === 0) {
    statusDetails = (
      <div>
        <div>{MSG_NOT_INSTALLED.para1}</div>
        {status === 'messaging-not-installed-android' ? (
          <ol>
            <li>
              {MSG_NOT_INSTALLED.androidAddStep}
              <i>build.gradle</i>
              <br />
              <br />
            </li>
            <li>
              {MSG_NOT_INSTALLED.importStep}
              <pre>
                <code>import com.adobe.marketing.mobile.Messaging;</code>
              </pre>
            </li>
            <li>
              {MSG_NOT_INSTALLED.androidRegisterStepPre} <i>onCreate()</i>{' '}
              {MSG_NOT_INSTALLED.androidRegisterStepPost}
              <pre>
                <code>Messaging.registerExtension();</code>
              </pre>
            </li>
          </ol>
        ) : (
          <ol>
            <li>
              {MSG_NOT_INSTALLED.iosAddStep}
              <br />
              <br />
            </li>
            <li>
              {MSG_NOT_INSTALLED.importStep}
              <pre>
                <code>import AEPMessaging</code>
              </pre>
            </li>
            <li>
              {MSG_NOT_INSTALLED.iosRegisterStepPre} <i>onCreate()</i>{' '}
              {MSG_NOT_INSTALLED.iosRegisterStepPost}
              <pre>
                <code>AEPMessaging.registerExtension();</code>
              </pre>
            </li>
          </ol>
        )}
        <div>
          {MSG_NOT_INSTALLED.forFull}&nbsp;
          <Link data-testid="openEnvironments" onPress={onOpenEnvironments}>
            {MSG_NOT_INSTALLED.visitLaunch}
          </Link>
        </div>
      </div>
    );
  } else if ((status || '').indexOf('no-token') === 0) {
    statusDetails = (
      <div>
        <div>{MSG_NO_TOKEN.para1}</div>
        {status === 'no-token-android' ? (
          <ol>
            <li>
              {MSG_NO_TOKEN.appNotSetup}
              <View margin="size-200">
                <Button data-testid="openHelp" onPress={onSetupAndroid} variant="secondary">
                  <Text>{MSG_NO_TOKEN.androidSetup}</Text>
                </Button>
              </View>
            </li>
            <li>
              {MSG_NO_TOKEN.missingSDK} <i>FirebaseMessaging.getInstance().getToken()</i>:
              <br />
              <pre>
                <code>MobileCore.setPushIdentifier(token);</code>
              </pre>
            </li>
          </ol>
        ) : (
          <ol>
            <li>
              {MSG_NO_TOKEN.appNotSetup}
              <View margin="size-200">
                <Button data-testid="openHelp" onPress={onSetupIos} variant="secondary">
                  <Text>{MSG_NO_TOKEN.iosSetup}</Text>
                </Button>
              </View>
            </li>
            <li>{MSG_NO_TOKEN.userDeclined}</li>
            <li>
              {MSG_NO_TOKEN.missingSDK} <i>didRegisterForRemoteNotificationsWithDeviceToken</i>:
              <br />
              <pre>
                <code>MobileCore.setPushIdentifier(token);</code>
              </pre>
            </li>
          </ol>
        )}
      </div>
    );
  } else if (status === 'edge-not-configured') {
    statusDetails = (
      <div>
        <div>{MSG_NO_EDGE.para1}</div>
        <Flex margin="size-200" gap="size-100" direction="column">
          <span>
            <Button data-testid="viewInstalled" variant="secondary" onPress={onOpenInstalled}>
              <Text>{MSG.viewInstalled}</Text>
            </Button>
          </span>
          <span>
            <Button data-testid="viewCatalog" variant="secondary" onPress={onOpenCatalog}>
              <Text>{MSG.viewCatalog}</Text>
            </Button>
          </span>
        </Flex>
        <div>{MSG_NO_EDGE.para2}</div>
        <View margin="size-200">
          <Button data-testid="viewPublishing" variant="secondary" onPress={onOpenPublishing}>
            <Text>{MSG.viewPublishing}</Text>
          </Button>
        </View>
        <div>
          {MSG_NO_EDGE.para3Pre} <i>edge.configId</i> {MSG_NO_EDGE.para3Post}
        </div>
      </div>
    );
  } else if (status === 'messaging-not-configured') {
    statusDetails = (
      <div>
        <div>{MSG_NO_CONFIG.para1}</div>
        <Flex margin="size-200" gap="size-100" direction="column">
          <span>
            <Button data-testid="viewInstalled" onPress={onOpenInstalled} variant="secondary">
              <Text>{MSG.viewInstalled}</Text>
            </Button>
          </span>
          <span>
            <Button data-testid="viewCatalog" onPress={onOpenCatalog} variant="secondary">
              <Text>{MSG.viewCatalog}</Text>
            </Button>
          </span>
        </Flex>
        <div>{MSG_NO_CONFIG.para2}</div>
        <View margin="size-200">
          <Button data-testid="viewPublishing" onPress={onOpenPublishing} variant="secondary">
            <Text>{MSG.viewPublishing}</Text>
          </Button>
        </View>
        <div>
          {MSG_NO_CONFIG.para3Pre} <i>messaging.*</i> {MSG_NO_CONFIG.para3Post}
        </div>
      </div>
    );
  } else {
    statusDetails = chooseStatusDetails(status) ? <div>{chooseStatusDetails(status)}</div> : null;
  }

  const statusText = chooseStatusMessage(status);
  const healthIconStatus = chooseStatus(status);

  return (
    <View>
      <Card {...extraProps}>
        <Heading marginTop="size-0">{MSG.title}</Heading>
        {isLoading ? (
          <Flex justifyContent="center" alignItems="center" height="100px">
            <ProgressCircle aria-label="Loading…" isIndeterminate />
          </Flex>
        ) : (
          <>
            <Text>{MSG.info}</Text>
            <Flex gap="size-100" alignItems="center" marginTop="size-200">
              {getHealthIcon(healthIconStatus, 'L')}
              <Heading level={4}>{statusText}</Heading>
            </Flex>
            {statusDetails && <View marginTop="size-200">{statusDetails}</View>}
            
          
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 16 }}>
              <tbody>
                {dataRows.map(row => (
                  <tr key={row.label} style={{ borderBottom: '1px solid #e1e1e1' }}>
                    <td style={{ fontWeight: 500, padding: '12px 16px' }}>{row.label}</td>
                    <td
                      style={{
                        padding: '12px 16px',
                        maxWidth: row.isLongData ? 300 : undefined,
                        wordBreak: row.isLongData ? 'break-all' : undefined
                      }}
                    >
                      {row.showCopy ? <CopyableValue value={row.value} /> : renderValue(row.value)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>  
            {/* Live Activities Validation Section */}
            <View marginTop="size-300">
              <View paddingTop="size-200">
                <LiveActivitiesValidationSection />
              </View>
            </View>
            
          </>
        )}
      </Card>
    </View>
  );
};

export default DeviceWidget;
